### PR TITLE
Add "Show/Hide" button for the table of running machines 

### PR DESCRIPTION
**Pull request by ppigazzini**
Whit a high number of CPU contributors the table of running machines is very long,
to view the tables of running tests and finished tests is required some scrolling.

Add a "Show/Hide" button for the table of running machines,
the page is loaded with the table hidden.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@ianfab ATM for multi variant this feature is over killer, but I viewed your tumb-up on official fishtest: up to you if merge or discard this PR

**Comment by ianfab** [comment]
@ppigazzini Thanks, I think it is very useful for official fishtest, but I agree that it is not really necessary here at the moment. Anyway, I'll keep this open and might merge it at a later point.

**Comment by ianfab** [comment]
Merged via merge of upstream changes https://github.com/ianfab/fishtest/commit/f366b48ea036a90ff42424262366b85f875ab48a.

**Comment by ppigazzini** [comment]
@ianfab I manually deleted the branch when Gary merged the PR upstream. I forgot that there were also this PR open. Sorry for the problem Fabian.
Pasquale

**Comment by ianfab** [comment]
@ppigazzini No problem at all. I merged it from upstream, so I would have closed this PR anyway.

**Pull request closed without merging**
