### PR TITLE
Fix cutechess warning for opening repetitions

### PR DESCRIPTION
**Pull request by ppigazzini**
Fix the "Warning: 2 opening repetitions vs 1 games per encounter"

### CODE REVIEW

**Comment by ianfab** [comment]
Thanks. I am wondering though, can this cause issues when there is an odd number of games? E.g., let's say we use batch size 200, but a worker drops out after 101 games. Another worker picks it up and plays 99/2*2=98 games. The next worker picking up the remaining game of the batch might then even run an invalid command with 0 rounds.

**Comment by ppigazzini** [comment]
@ianfab good question. Official fishtest has been running with this change from the start of 2020, see https://github.com/glinscott/fishtest/pull/538

I'm wondering if the result update to the server is done always with couple of games.

**Comment by ianfab** [comment]
I can imagine two possible reasons:
- Due to the introduction of the pentanomial model, games always need to be submitted in pairs, so odd numbers are impossible.
- Continuation of incomplete batches might be disabled. I think I remember something like that, but can not find anything related to that right now.

**Comment by ppigazzini** [comment]
Correct, pentanomial model was introduced in December 2019 (and not March 2020 as I wrongly remembered) so that cutechess-cli change worked because the update with pairs of games: serendipity happens.

From cutechess-cli help:
```
  -rounds N  Multiply the number of rounds to play by N.
             For two-player tournaments this option should be used
             to set the total number of games to play.
```
I'm to close this buggy PR :)

**Comment by ppigazzini** [comment]
@ianfab cutechess-cli doesn't print the warning when using `-repeat -games <games_to_play>` instead that `-repeat -rounds <games_to_play>`

**Comment by ppigazzini** [comment]
PR updated but set to draft.
I will verify if using `-games` cutechess-cli is repeating the openings.

**Comment by ppigazzini** [comment]
@ianfab `-games` repeat the openings, no warning with even `games_to_play`, warning with odd `games_to_play`.
BTW with odd `games_to_play` any options combination triggers the warning.

**Comment by ianfab** [comment]
Thanks

**Pull request merged**
