### PR TITLE
Set the best compiler CPU architecture

### PR DESCRIPTION
**Pull request by ppigazzini**
Find the best compiler CPU architecture compatible with hardware CPU
(e.g. x86-64-avx2 on AMD zen ,x86-64-bmi2 on Haswell) and with the Makefile supported targets.
Remove custom_make.txt

Copy and paste of several @vondele commits in official fishtest.

### CODE REVIEW

**Comment by ppigazzini** [comment]
@ianfab let me know if:
 - all your projects have Makefile with targets
 - it's fine to remove custom_make.txt

**Comment by ianfab** [comment]
Thanks. I think removing the custom_make and by that enforcing g++ and profile-build should be fine. I will check regarding the make targets, but it is likely that not all of them are supported everywhere, although now except Fairy-SF most forks are dead anyways. However, I am wondering how official fishtest deals with that, because I think especially the vector targets are rather new, so can't regression tests against older SF versions potentially fail on some machines?

**Comment by ppigazzini** [comment]
Yes, better to double check and make some tests, I don't know the recent SF Makefile structure.

IMO to avoid indentation errors in copy and paste from official fishtest will be useful to reformat variant fishtest code with
```
black --exclude=worker/requests .
isort --profile black --skip worker/requests .
```

**Comment by ppigazzini** [comment]
@ianfab BTW my workers (x86-64-bmi2, x86-64-modern, x86-64-ssse3 - wsl, msys2, ubuntu) are running with this PR.

**Pull request merged**
