### PR TITLE
Reformat worker code with black and isort

### PR DESCRIPTION
**Pull request by ppigazzini**
```
black --exclude=worker/requests .
isort --profile black --skip worker/requests .
```

This helps to have a shorter output from linters (flake8, pylint etc.).

### CODE REVIEW

**Comment by ppigazzini** [comment]
@ianfab this is the worker code reformatted. At first it's a bit strange, after a while is very readable.

**Comment by ppigazzini** [comment]
@ianfab I set this as draft waiting the merge of more important PR and, of course, your opinion :)

BTW black was unable to reformat 2 files (builder.py, stat_util.py), solved running `black --fast --exclude=requests .`
There is a dozen of open Issues on black github about this bug :)

**Comment by ianfab** [comment]
Looks like the last merge caused a conflict, sorry. Could you please merge/rebase?

So this reformatting was also applied to official fishtest, which makes it easier to port/merge changes, right?

**Comment by ppigazzini** [comment]
@ianfab rebased.

**Comment by ppigazzini** [comment]
Yes, with reformat will be more error proof to copy code from official :)

**Comment by ianfab** [comment]
Server updated.

**Pull request merged**
