### PR TITLE
Make the worker Python3 compatible

### PR DESCRIPTION
**Pull request by ppigazzini**
python 2 is EOL from 1 Jan 2020

Show python version to server.

Update `requests` package for python3 compatibility.

### CODE REVIEW

**Comment by gbtami** [comment]
Why don't use upstream request lib?

**Comment by ppigazzini** [comment]
@gbtami the `requests` lib from the @ianfab master is not compatible with python3, so I copied the `requests` lib from @glinscott master. IMO the best solution is to install the latest `requests` lib client side with pip and delete it from github, see:
```bash
git clone https://github.com/ianfab/fishtest.git
cd fishtest/
git pull --no-edit origin pull/20/head
cd worker/
python3 -m venv env
env/bin/python3 -m pip install --upgrade pip setuptools wheel requests
```

**Comment by ianfab** [comment]
@ppigazzini Thanks a lot! Migration was overdue, but I struggled to find the time, so that is highly appreciated. As far as I have seen you already tested to connect workers with several different python versions to the current server. Can you briefly list which OS+python combinations you tested?

**Comment by ppigazzini** [comment]
@ianfab with `pyenv` it's easy to test any python version on linux. At the moment I tested:
| os | python |
| - | - |
| ubuntu 20.02 | 2.7.18 3.9.2 |
| windows msys2 | 3.8.8 |

**Comment by ppigazzini** [comment]
@ianfab:
- updated table with tested os/python combo
- wiki worker pages updated with instructions for python3

**Pull request merged**
