### PR TITLE
Update Documentation for Multi Variant Fishtest

### PR DESCRIPTION
**Pull request by ppigazzini**
Update README.md with information about Multi Variant Fishtest.
Add instructions to setup a fishtest server and a fishtest worker.
Delete old/not applicable information.

### CODE REVIEW

**Comment by ianfab** [comment]
Thanks a lot for your contributions. I do not have time to review this PR in the next days though, so it might take a while before I can merge this.

**Comment by ppigazzini** [comment]
No problem. Anyway Readme is very short, and the setups for worker/server are a copy of the MVSF wiki pages. You could enable the MVFT wiki and delete the .md files from the repo.

**Comment by ianfab** [comment]
I enabled the wiki, so feel free to edit it. Thanks again for your contributions.

**Comment by ppigazzini** [comment]
@ianfab I don't find the "Edit" button, I think that ATM the wiki is only editable by you.

**Comment by ianfab** [comment]
@ppigazzini Oh, I forgot to deselect that option. Should work now.

**Comment by ppigazzini** [comment]
@ianfab thank you, added some pages to the Wiki, now the PR has only the Readme file

**Pull request merged**
